<a href="https://colab.research.google.com/github/shuklasatyam9568-coder/python-code-project/blob/main/Eda_of_youtube_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

Case Study 1 : Analyzing YouTube Growth Trends Across Countries
Background:

You’re a data analyst working for a global media company studying the influence of education and urbanization on YouTube content creation.

The company wants to understand how different countries perform based on certain socio-economic factors and YouTube metrics.

🧠 Questions:

Reading & Boolean Indexing
Filter and display all YouTubers from India whose Unemployment rate is below 6% and who have more than 5 million subscribers.
Indexing & Slicing + Unique
List the first 5 YouTubers (rows) using slicing.

Then, print the unique channel types in the dataset.

Value_counts + Boolean Indexing
Identify the top 3 most common categories on YouTube.

Then, count how many YouTubers belong to the 'Entertainment' category.

In [3]:
df=pd.read_csv('/content/drive/MyDrive/csv files project/youtube.csv')

In [5]:
df.head(5)

,Unnamed: 0,Country,Gross tertiary education enrollment (%),Population,Title,Unemployment rate,Urban_population,Youtuber,category,channel_type,...,lowest_yearly_earnings,rank,subscribers,subscribers_for_last_30_days,uploads,video views,video_views_for_the_last_30_days,video_views_rank,engagement_rate,views_per_upload
0,0,India,28.1,1.366418e+09,T-Series,5.36,471031528.0,T-Series,Music,Music,...,6800000.0,1,245000000,2000000.0,20082,2.280000e+11,2.258000e+09,1.0,0.816327,1.135345e+07
1,2,United States,88.2,3.282395e+08,MrBeast,14.70,270663028.0,MrBeast,Entertainment,Entertainment,...,4000000.0,3,166000000,8000000.0,741,2.836884e+10,1.348000e+09,48.0,4.819277,3.828454e+07
2,3,United States,88.2,3.282395e+08,Cocomelon - Nursery Rhymes,14.70,270663028.0,Cocomelon - Nursery Rhymes,Education,Education,...,5900000.0,4,162000000,1000000.0,966,1.640000e+11,1.975000e+09,2.0,0.617284,1.697723e+08
3,4,India,28.1,1.366418e+09,SET India,5.36,471031528.0,SET India,Shows,Entertainment,...,5500000.0,5,159000000,1000000.0,116536,1.480000e+11,1.824000e+09,3.0,0.628931,1.269994e+06
4,8,Russia,81.9,1.443735e+08,Like Nastya Vlog,4.59,107683889.0,Like Nastya,People & Blogs,People,...,146800.0,9,106000000,100000.0,493,9.047906e+10,4.894700e+07,630.0,0.094340,1.835275e+08

In [6]:
df.describe()

,Unnamed: 0,Gross tertiary education enrollment (%),Population,Unemployment rate,Urban_population,channel_type_rank,country_rank,created_date,created_year,highest_monthly_earnings,...,lowest_yearly_earnings,rank,subscribers,subscribers_for_last_30_days,uploads,video views,video_views_for_the_last_30_days,video_views_rank,engagement_rate,views_per_upload
count,554.000000,554.000000,5.540000e+02,554.000000,5.540000e+02,554.000000,554.000000,554.000000,554.000000,5.540000e+02,...,5.540000e+02,554.000000,5.540000e+02,5.540000e+02,554.000000,5.540000e+02,5.540000e+02,5.540000e+02,554.000000,5.540000e+02
mean,462.828520,60.533574,4.965559e+08,8.866029,2.402031e+08,238.034296,180.850181,15.259928,2012.492780,8.409689e+05,...,6.307215e+05,463.828520,2.462401e+07,3.431256e+05,14758.036101,1.310608e+10,2.387087e+08,1.297121e+05,1.497291,8.737511e+07
std,289.929893,26.365440,5.178813e+08,4.813768,1.641213e+08,937.109139,732.093496,8.771828,4.468591,1.216598e+06,...,9.120686e+05,289.929893,1.950924e+07,5.881429e+05,44248.913413,1.729334e+10,4.862804e+08,6.815954e+05,2.196131,1.008783e+09
min,0.000000,7.600000,2.025060e+05,0.750000,3.558800e+04,1.000000,1.000000,1.000000,1970.000000,0.000000e+00,...,0.000000e+00,1.000000,1.230000e+07,1.000000e+00,1.000000,2.634000e+03,3.000000e+00,1.000000e+00,0.000005,2.634000e+03
25%,205.500000,28.100000,1.023202e+08,5.360000,5.770569e+07,19.000000,10.000000,8.000000,2009.000000,1.862750e+05,...,1.397750e+05,206.500000,1.490000e+07,1.000000e+05,436.500000,5.102920e+09,4.906325e+07,2.222500e+02,0.560237,1.790264e+06
50%,447.500000,60.000000,3.282395e+08,5.560000,2.706630e+08,48.000000,40.500000,15.000000,2013.000000,4.521000e+05,...,3.391000e+05,448.500000,1.880000e+07,2.000000e+05,1278.000000,9.040989e+09,1.150635e+08,5.695000e+02,0.777352,6.163724e+06
75%,701.750000,88.200000,1.366418e+09,14.700000,4.710315e+08,114.500000,104.750000,22.000000,2015.750000,9.414000e+05,...,7.060000e+05,702.750000,2.670000e+07,4.000000e+05,4142.500000,1.540470e+10,2.380330e+08,1.580500e+03,1.566174,1.873773e+07
max,994.000000,113.100000,1.397715e+09,14.720000,8.429340e+08,7670.000000,7683.000000,31.000000,2022.000000,9.200000e+06,...,6.900000e+06,995.000000,2.450000e+08,8.000000e+06,301308.000000,2.280000e+11,6.589000e+09,4.054962e+06,34.183673,2.293663e+10

In [31]:
# Reading & Boolean Indexing
# Filter and display all YouTubers from India
# whose Unemployment rate is below 6% and who have more than 5 million subscribers.
condition=(df['Country']== 'India')&((df['Unemployment rate'] < 6) & (df['subscribers'] > 5000000))

In [35]:
df[condition]

/tmp/ipykernel_2652/3978456370.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[condition]

,Unnamed: 0,Country,Gross tertiary education enrollment (%),Population,Title,Unemployment rate,Urban_population,Youtuber,category,channel_type,...,lowest_yearly_earnings,rank,subscribers,subscribers_for_last_30_days,uploads,video views,video_views_for_the_last_30_days,video_views_rank,engagement_rate,views_per_upload
0,0,India,28.1,1.366418e+09,T-Series,5.36,471031528.0,T-Series,Music,Music,...,6800000.0,1,245000000,2000000.0,20082,2.280000e+11,2.258000e+09,1.0,0.816327,1.135345e+07
3,4,India,28.1,1.366418e+09,SET India,5.36,471031528.0,SET India,Shows,Entertainment,...,5500000.0,5,159000000,1000000.0,116536,1.480000e+11,1.824000e+09,3.0,0.628931,1.269994e+06
6,10,India,28.1,1.366418e+09,Zee Music Company,5.36,471031528.0,Zee Music Company,Music,Music,...,2400000.0,11,96700000,1100000.0,8548,5.785629e+10,8.036130e+08,12.0,1.137539,6.768401e+06
9,15,India,28.1,1.366418e+09,Sony SAB,5.36,471031528.0,Sony SAB,Shows,Entertainment,...,5000000.0,16,83000000,1100000.0,71270,1.010000e+11,1.657000e+09,4.0,1.325301,1.417146e+06
13,21,India,28.1,1.366418e+09,Zee TV,5.36,471031528.0,Zee TV,Entertainment,Entertainment,...,5100000.0,22,70500000,900000.0,129204,7.313905e+10,1.707000e+09,9.0,1.276596,5.660742e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,964,India,28.1,1.366418e+09,Flowers Comedy,5.36,471031528.0,Flowers Comedy,Entertainment,Entertainment,...,540100.0,965,12500000,100000.0,11907,1.169108e+10,1.800210e+08,337.0,0.800000,9.818662e+05
546,980,India,28.1,1.366418e+09,Zee Kids,5.36,471031528.0,Zee Kids,Film & Animation,Entertainment,...,285500.0,981,12400000,100000.0,1212,7.683670e+09,9.516300e+07,709.0,0.806452,6.339662e+06
547,984,India,28.1,1.366418e+09,bharatzkitchen HINDI,5.36,471031528.0,bharatzkitchen HINDI,Howto & Style,Howto,...,92900.0,985,12400000,100000.0,729,2.315227e+09,3.096800e+07,4042.0,0.806452,3.175894e+06
551,991,India,28.1,1.366418e+09,Free Fire India Official,5.36,471031528.0,Free Fire India Official,People & Blogs,Games,...,194200.0,992,12300000,300000.0,1500,1.674410e+09,6.473500e+07,6141.0,2.439024,1.116273e+06
553,994,India,28.1,1.366418e+09,Make Joke Of,5.36,471031528.0,Make Joke Of,Comedy,Comedy,...,72000.0,995,12300000,100000.0,62,2.129774e+09,2.400000e+07,4568.0,0.813008,3.435119e+07

In [45]:
#whose Unemployment rate is below 6% and who have more than 5 million subscribers.
df.reset_index(drop=True,inplace=True)
df

,Unnamed: 0,Country,Gross tertiary education enrollment (%),Population,Title,Unemployment rate,Urban_population,Youtuber,category,channel_type,...,lowest_yearly_earnings,rank,subscribers,subscribers_for_last_30_days,uploads,video views,video_views_for_the_last_30_days,video_views_rank,engagement_rate,views_per_upload
0,0,India,28.1,1.366418e+09,T-Series,5.36,471031528.0,T-Series,Music,Music,...,6800000.0,1,245000000,2000000.0,20082,2.280000e+11,2.258000e+09,1.0,0.816327,1.135345e+07
1,4,India,28.1,1.366418e+09,SET India,5.36,471031528.0,SET India,Shows,Entertainment,...,5500000.0,5,159000000,1000000.0,116536,1.480000e+11,1.824000e+09,3.0,0.628931,1.269994e+06
2,10,India,28.1,1.366418e+09,Zee Music Company,5.36,471031528.0,Zee Music Company,Music,Music,...,2400000.0,11,96700000,1100000.0,8548,5.785629e+10,8.036130e+08,12.0,1.137539,6.768401e+06
3,15,India,28.1,1.366418e+09,Sony SAB,5.36,471031528.0,Sony SAB,Shows,Entertainment,...,5000000.0,16,83000000,1100000.0,71270,1.010000e+11,1.657000e+09,4.0,1.325301,1.417146e+06
4,21,India,28.1,1.366418e+09,Zee TV,5.36,471031528.0,Zee TV,Entertainment,Entertainment,...,5100000.0,22,70500000,900000.0,129204,7.313905e+10,1.707000e+09,9.0,1.276596,5.660742e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,964,India,28.1,1.366418e+09,Flowers Comedy,5.36,471031528.0,Flowers Comedy,Entertainment,Entertainment,...,540100.0,965,12500000,100000.0,11907,1.169108e+10,1.800210e+08,337.0,0.800000,9.818662e+05
135,980,India,28.1,1.366418e+09,Zee Kids,5.36,471031528.0,Zee Kids,Film & Animation,Entertainment,...,285500.0,981,12400000,100000.0,1212,7.683670e+09,9.516300e+07,709.0,0.806452,6.339662e+06
136,984,India,28.1,1.366418e+09,bharatzkitchen HINDI,5.36,471031528.0,bharatzkitchen HINDI,Howto & Style,Howto,...,92900.0,985,12400000,100000.0,729,2.315227e+09,3.096800e+07,4042.0,0.806452,3.175894e+06
137,991,India,28.1,1.366418e+09,Free Fire India Official,5.36,471031528.0,Free Fire India Official,People & Blogs,Games,...,194200.0,992,12300000,300000.0,1500,1.674410e+09,6.473500e+07,6141.0,2.439024,1.116273e+06
138,994,India,28.1,1.366418e+09,Make Joke Of,5.36,471031528.0,Make Joke Of,Comedy,Comedy,...,72000.0,995,12300000,100000.0,62,2.129774e+09,2.400000e+07,4568.0,0.813008,3.435119e+07

In [43]:
# Indexing & Slicing + Unique
# List the first 5 YouTubers (rows) using slicing.

# Then, print the unique channel types in the dataset.

In [50]:
df.loc[0:4,['Youtuber']]

            Youtuber
0           T-Series
1          SET India
2  Zee Music Company
3           Sony SAB
4             Zee TV

In [51]:
list(enumerate(df.columns))

[(0, 'Unnamed: 0'),
 (1, 'Country'),
 (2, 'Gross tertiary education enrollment (%)'),
 (3, 'Population'),
 (4, 'Title'),
 (5, 'Unemployment rate'),
 (6, 'Urban_population'),
 (7, 'Youtuber'),
 (8, 'category'),
 (9, 'channel_type'),
 (10, 'channel_type_rank'),
 (11, 'country_rank'),
 (12, 'created_date'),
 (13, 'created_month'),
 (14, 'created_year'),
 (15, 'highest_monthly_earnings'),
 (16, 'highest_yearly_earnings'),
 (17, 'lowest_monthly_earnings'),
 (18, 'lowest_yearly_earnings'),
 (19, 'rank'),
 (20, 'subscribers'),
 (21, 'subscribers_for_last_30_days'),
 (22, 'uploads'),
 (23, 'video views'),
 (24, 'video_views_for_the_last_30_days'),
 (25, 'video_views_rank'),
 (26, 'engagement_rate'),
 (27, 'views_per_upload')]

In [52]:
df.iloc[0:5, 7]
# .iloc --> start: stop , here stop is exclusive

0             T-Series
1            SET India
2    Zee Music Company
3             Sony SAB
4               Zee TV
Name: Youtuber, dtype: object

In [53]:
df['Youtuber'].head() # Simplest way of getting top n,

0             T-Series
1            SET India
2    Zee Music Company
3             Sony SAB
4               Zee TV
Name: Youtuber, dtype: object

In [54]:
# Then, print the unique channel types in the dataset.
df['channel_type'].unique()

array(['Music', 'Entertainment', 'Education', 'News', 'Comedy', 'Film',
       'Tech', 'Howto', 'People', 'Games'], dtype=object)

In [55]:
# How many unique channel types are there in data?
len(df['channel_type'].unique())

10

In [ ]:
# Value_counts + Boolean Indexing
# Identify the top 3 most common categories on YouTube.

# Then, count how many YouTubers belong to the 'Entertainment' category.

In [58]:
df.columns

Index(['Unnamed: 0', 'Country', 'Gross tertiary education enrollment (%)',
       'Population', 'Title', 'Unemployment rate', 'Urban_population',
       'Youtuber', 'category', 'channel_type', 'channel_type_rank',
       'country_rank', 'created_date', 'created_month', 'created_year',
       'highest_monthly_earnings', 'highest_yearly_earnings',
       'lowest_monthly_earnings', 'lowest_yearly_earnings', 'rank',
       'subscribers', 'subscribers_for_last_30_days', 'uploads', 'video views',
       'video_views_for_the_last_30_days', 'video_views_rank',
       'engagement_rate', 'views_per_upload'],
      dtype='object')

In [67]:
df['category'].value_counts()

category
Entertainment           39
Music                   26
Education               14
Comedy                  14
People & Blogs          11
News & Politics         10
Film & Animation         9
Shows                    5
Science & Technology     3
Howto & Style            3
Trailers                 2
Movies                   2
Gaming                   1
Name: count, dtype: int64

In [74]:
df2=df['category'].value_counts()

In [75]:
# How do I make the category which is row index name to column?

df2.reset_index()

                category  count
0          Entertainment     39
1                  Music     26
2              Education     14
3                 Comedy     14
4         People & Blogs     11
5        News & Politics     10
6       Film & Animation      9
7                  Shows      5
8   Science & Technology      3
9          Howto & Style      3
10              Trailers      2
11                Movies      2
12                Gaming      1

In [76]:
#top3
df2.head(3)

category
Entertainment    39
Music            26
Education        14
Name: count, dtype: int64

Case Study 2: Cleaning & Organizing YouTube Earnings Data
Background: As a senior data engineer, you're responsible for cleaning and organizing the data so it’s ready for executive reporting. The management is particularly interested in sorting earnings, updating column names, and resetting index formats.

🧠 Questions:

Sort + Reset Index
Sort the data in descending order of highest_yearly_earnings, and reset the index after sorting.

Display the top 5 entries post-sort.

Rename + Replace
Rename the column highest_monthly_earnings to max_monthly_income and lowest_monthly_earnings to min_monthly_income.

Replace all occurrences of the Category Column - "People & Blogs" with "Personal Vlogs".

Set Index + Reset Index
Set Youtuber as the new index and display the data.

Then reset the index to bring it back to default.

In [ ]:
# Sort + Reset Index
# Sort the data in descending order of
# highest_yearly_earnings, and reset the index after sorting.

# Display the top 5 entries post-sort.

In [96]:
df.sort_values(by='highest_yearly_earnings',ascending=False,inplace=True)

In [100]:
df.reset_index(drop=True,inplace=True)

In [102]:
df.head(5)

,Unnamed: 0,Country,Gross tertiary education enrollment (%),Population,Title,Unemployment rate,Urban_population,Youtuber,category,channel_type,...,lowest_yearly_earnings,rank,subscribers,subscribers_for_last_30_days,uploads,video views,video_views_for_the_last_30_days,video_views_rank,engagement_rate,views_per_upload
0,0,India,28.1,1.366418e+09,T-Series,5.36,471031528.0,T-Series,Music,Music,...,6800000.0,1,245000000,2000000.0,20082,2.280000e+11,2.258000e+09,1.0,0.816327,1.135345e+07
1,4,India,28.1,1.366418e+09,SET India,5.36,471031528.0,SET India,Shows,Entertainment,...,5500000.0,5,159000000,1000000.0,116536,1.480000e+11,1.824000e+09,3.0,0.628931,1.269994e+06
2,21,India,28.1,1.366418e+09,Zee TV,5.36,471031528.0,Zee TV,Entertainment,Entertainment,...,5100000.0,22,70500000,900000.0,129204,7.313905e+10,1.707000e+09,9.0,1.276596,5.660742e+05
3,139,India,28.1,1.366418e+09,StarPlus,5.36,471031528.0,StarPlus,Entertainment,Entertainment,...,5000000.0,140,32000000,1200000.0,44892,2.680067e+10,1.667000e+09,60.0,3.750000,5.970034e+05
4,15,India,28.1,1.366418e+09,Sony SAB,5.36,471031528.0,Sony SAB,Shows,Entertainment,...,5000000.0,16,83000000,1100000.0,71270,1.010000e+11,1.657000e+09,4.0,1.325301,1.417146e+06

In [ ]:
# Rename + Replace
# Rename the column highest_monthly_earnings to max_monthly_income and lowest_monthly_earnings to min_monthly_income.

# Replace all occurrences of the Category Column - "People & Blogs" with "Personal Vlogs".

In [110]:
df.rename(columns={'highest_monthly_earnings':'max_monthly_income','lowest_monthly_earnings':'min_monthly_income'},inplace=True)

In [114]:
df.columns

Index(['Unnamed: 0', 'Country', 'Gross tertiary education enrollment (%)',
       'Population', 'Title', 'Unemployment rate', 'Urban_population',
       'Youtuber', 'category', 'channel_type', 'channel_type_rank',
       'country_rank', 'created_date', 'created_month', 'created_year',
       'max_monthly_income', 'highest_yearly_earnings', 'min_monthly_income',
       'lowest_yearly_earnings', 'rank', 'subscribers',
       'subscribers_for_last_30_days', 'uploads', 'video views',
       'video_views_for_the_last_30_days', 'video_views_rank',
       'engagement_rate', 'views_per_upload'],
      dtype='object')

In [121]:
df['category'].head(10)

0             Music
1             Shows
2     Entertainment
3     Entertainment
4             Shows
5             Shows
6    People & Blogs
7     Entertainment
8         Education
9             Music
Name: category, dtype: object

In [123]:
df['category'].replace('People & Blogs','Personal Vlogs').head(9)

0             Music
1             Shows
2     Entertainment
3     Entertainment
4             Shows
5             Shows
6    Personal Vlogs
7     Entertainment
8         Education
Name: category, dtype: object

In [ ]:
# Set Index + Reset Index
# Set Title as the new index and display the data.

# Then reset the index to bring it back to default.

In [140]:
df.set_index('Title',inplace=True)

In [143]:
df.reset_index()

,Title,Unnamed: 0,Country,Gross tertiary education enrollment (%),Population,Unemployment rate,Urban_population,category,channel_type,channel_type_rank,...,lowest_yearly_earnings,rank,subscribers,subscribers_for_last_30_days,uploads,video views,video_views_for_the_last_30_days,video_views_rank,engagement_rate,views_per_upload
0,RKD Studios,419,India,28.1,1.366418e+09,5.36,471031528.0,Entertainment,Entertainment,108.0,...,0.0,420,19500000,300000.0,847,5.234251e+09,5.984100e+07,1265.0,1.538462,6.179753e+06
1,Ultra Movie Parlour,298,India,28.1,1.366418e+09,5.36,471031528.0,Movies,Film,22.0,...,0.0,299,22900000,300000.0,1670,5.320485e+09,1.188460e+08,1248.0,1.310044,3.185919e+06
2,Ultra Bollywood,99,India,28.1,1.366418e+09,5.36,471031528.0,Trailers,Entertainment,31.0,...,0.0,100,36600000,200000.0,9168,1.565379e+10,1.314620e+08,205.0,0.546448,1.707437e+06
3,Green Gold TV - Official Channel,404,India,28.1,1.366418e+09,5.36,471031528.0,Film & Animation,Entertainment,104.0,...,0.0,405,20000000,100000.0,1476,9.715292e+09,7.027800e+07,473.0,0.500000,6.582176e+06
4,Prajapati News,533,India,28.1,1.366418e+09,5.36,471031528.0,Comedy,Entertainment,128.0,...,22900.0,534,17000000,100000.0,1407,1.001465e+09,7.626000e+06,11662.0,0.588235,7.117736e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,Sony SAB,15,India,28.1,1.366418e+09,5.36,471031528.0,Shows,Entertainment,7.0,...,5000000.0,16,83000000,1100000.0,71270,1.010000e+11,1.657000e+09,4.0,1.325301,1.417146e+06
135,StarPlus,139,India,28.1,1.366418e+09,5.36,471031528.0,Entertainment,Entertainment,40.0,...,5000000.0,140,32000000,1200000.0,44892,2.680067e+10,1.667000e+09,60.0,3.750000,5.970034e+05
136,Zee TV,21,India,28.1,1.366418e+09,5.36,471031528.0,Entertainment,Entertainment,8.0,...,5100000.0,22,70500000,900000.0,129204,7.313905e+10,1.707000e+09,9.0,1.276596,5.660742e+05
137,SET India,4,India,28.1,1.366418e+09,5.36,471031528.0,Shows,Entertainment,2.0,...,5500000.0,5,159000000,1000000.0,116536,1.480000e+11,1.824000e+09,3.0,0.628931,1.269994e+06
138,T-Series,0,India,28.1,1.366418e+09,5.36,471031528.0,Music,Music,1.0,...,6800000.0,1,245000000,2000000.0,20082,2.280000e+11,2.258000e+09,1.0,0.816327,1.135345e+07

In [144]:
# Then reset the index to bring it back to default.
df.reset_index(drop = True) # No , what's the issue? --> Column Youtuber will be dropped

,Unnamed: 0,Country,Gross tertiary education enrollment (%),Population,Unemployment rate,Urban_population,category,channel_type,channel_type_rank,country_rank,...,lowest_yearly_earnings,rank,subscribers,subscribers_for_last_30_days,uploads,video views,video_views_for_the_last_30_days,video_views_rank,engagement_rate,views_per_upload
0,419,India,28.1,1.366418e+09,5.36,471031528.0,Entertainment,Entertainment,108.0,74.0,...,0.0,420,19500000,300000.0,847,5.234251e+09,5.984100e+07,1265.0,1.538462,6.179753e+06
1,298,India,28.1,1.366418e+09,5.36,471031528.0,Movies,Film,22.0,61.0,...,0.0,299,22900000,300000.0,1670,5.320485e+09,1.188460e+08,1248.0,1.310044,3.185919e+06
2,99,India,28.1,1.366418e+09,5.36,471031528.0,Trailers,Entertainment,31.0,26.0,...,0.0,100,36600000,200000.0,9168,1.565379e+10,1.314620e+08,205.0,0.546448,1.707437e+06
3,404,India,28.1,1.366418e+09,5.36,471031528.0,Film & Animation,Entertainment,104.0,72.0,...,0.0,405,20000000,100000.0,1476,9.715292e+09,7.027800e+07,473.0,0.500000,6.582176e+06
4,533,India,28.1,1.366418e+09,5.36,471031528.0,Comedy,Entertainment,128.0,89.0,...,22900.0,534,17000000,100000.0,1407,1.001465e+09,7.626000e+06,11662.0,0.588235,7.117736e+05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,15,India,28.1,1.366418e+09,5.36,471031528.0,Shows,Entertainment,7.0,5.0,...,5000000.0,16,83000000,1100000.0,71270,1.010000e+11,1.657000e+09,4.0,1.325301,1.417146e+06
135,139,India,28.1,1.366418e+09,5.36,471031528.0,Entertainment,Entertainment,40.0,38.0,...,5000000.0,140,32000000,1200000.0,44892,2.680067e+10,1.667000e+09,60.0,3.750000,5.970034e+05
136,21,India,28.1,1.366418e+09,5.36,471031528.0,Entertainment,Entertainment,8.0,6.0,...,5100000.0,22,70500000,900000.0,129204,7.313905e+10,1.707000e+09,9.0,1.276596,5.660742e+05
137,4,India,28.1,1.366418e+09,5.36,471031528.0,Shows,Entertainment,2.0,2.0,...,5500000.0,5,159000000,1000000.0,116536,1.480000e+11,1.824000e+09,3.0,0.628931,1.269994e+06
138,0,India,28.1,1.366418e+09,5.36,471031528.0,Music,Music,1.0,1.0,...,6800000.0,1,245000000,2000000.0,20082,2.280000e+11,2.258000e+09,1.0,0.816327,1.135345e+07